### ISSUE TITLE
Add adapter-tests

### ISSUE THREAD

**Issue by fratzinger** [ps73/feathers-prisma#1]
This is amazing! Thanks for your work! 🚀
Do you know about `@feathersjs/adapter-tests`? 
It's an official package to check adapters against common use cases. Please have a look at 
- https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/test/index.test.js#L13
- https://github.com/feathersjs-ecosystem/feathers-knex/blob/master/test/index.test.js#L11
- https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/master/test/index.test.js#L10

What do you think? Are you interested to add `adapter-tests` to this package? That would make this package even more reliable.

**Comment by ps73** [comment]
Hi @fratzinger 

thanks for your kind advice. Didn't know anything about @feathersjs/adapter-tests yet.
I will have a look into it and definitely adding it to this package!

**Comment by fratzinger** [comment]
Nice, thanks for your quick reply and openness :)
prisma was discussed on [slack.feathersjs.com](http://slack.feathersjs.com/) a few times. Nice to see someone doing the work!

**Comment by fratzinger** [comment]
nice! Great work!
