### ISSUE TITLE
no prisma.schema generated

### ISSUE THREAD

**Issue by rizen** [ps73/feathers-prisma#10]
### Steps to reproduce

When you run ```feathers generate app``` and select prisma as the ORM no schema.prisma is generated, but it does generate some service and class modules. 

### Expected behavior

schema.prisma would be generated to go along with the users.service and users.class modules and hooked into the starter app. Alternatively some sort of documentation for that portion of it so that the normal prisma commands could work from the command line.

I can run ```npx prisma init``` to generate a schema file, but by default it is referencing .env for it's database URL, while the feather's config also has a database URL in its config. And I could add fields to that schema, but if you select something like Sequelize when initing feathers, it creates a model file with all the appropriate fields for the auth classes that you've selected. So I was expecting a similar experience to that. 

### Actual behavior

Some modules get generated that theoretically will use prisma, but despite knowing a bit about both feathers and prisma, I fail to see what I'm supposed to do next.

### System configuration

Just installed feathers and ran ```feathers generate app``` .

**Module versions** the latest of everything 

**NodeJS version**: v16.15.1 (LTS)

**Operating System**: Mac OS 12.3.1

**Browser Version**: N/A

**React Native Version**: N/A

**Module Loader**: N/A

**Comment by rizen** [comment]
I should say here that this isn't a support request. I did create my own prisma schema and run a migration to create it. It just seemed like the setup stopped short of where the other ORMs did.

**Comment by ps73** [comment]
Hi, will close this issue because it is more a todo for the [feathers generator](https://github.com/feathersjs/generator-feathers)
