### ISSUE TITLE
Prisma Client error 'PrismaClientUnknownRequestError' is not handled and results in an error of undefined

### ISSUE THREAD

**Issue by NLaza** [ps73/feathers-prisma#11]
The [error handler](https://github.com/ps73/feathers-prisma/blob/5cc6cfe51c991e0f9c713a1e21596f46bd16ee20/src/error-handler.ts) is not handling the error `PrismaClientUnknownRequestError`. This causes the variable `feathersError` in the [error handler](https://github.com/ps73/feathers-prisma/blob/5cc6cfe51c991e0f9c713a1e21596f46bd16ee20/src/error-handler.ts) to remain `undefined`, because no default error is set. Because of the `undefined` error the error cannot be processed correctly by feathers. 

The error can be reproduced by, for example, sending a query that contains an integer value that is too large.

**Module versions**: `0.5.8`

**NodeJS version**: `16.15.1`

**Comment by ps73** [comment]
Fixed in 0.6.0
