### ISSUE TITLE
Automatic conversion of fields to numbers leads to errors (e.g. for GoogleOauthIDs or Ethereum Addresses)

### ISSUE THREAD

**Issue by pineappledafruitdude** [ps73/feathers-prisma#12]
### Steps to reproduce

Strings that contain numbers are automatically converted to numbers, this is sometimes not the desired behavior.

```js
Service.create({ googleId: "123456789" })
// --> { googleId: 123456789 }
```
Or
```js
Service.create({ ethereumAddress: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F" })
// --> { ethereumAddress: 6.4956264143494794e+47 }
```

### Expected behavior

Strings should not be converted to numbers

### Actual behavior

Strings are converted to numbers

### System configuration

**Module versions** 
0.5.8

**NodeJS version**:
v16.13.1

**Operating System**:
Mac

**Browser Version**:
Chrome

**Comment by ps73** [comment]
Fixed in 0.6.0
