### ISSUE TITLE
Some errors are not communicated to the frontend client.

### ISSUE THREAD

**Issue by harijoe** [ps73/feathers-prisma#5]
### Steps to reproduce

- Create a user model missing a property called for example `missing_property_in_schema`
- Trigger a `PrismaClientValidationError` by calling for example `service('users').create({ missing_property_in_schema: 'some_value' })`

### Expected behavior

The current returned error is : 
![image](https://user-images.githubusercontent.com/10897494/150655769-cd37953b-d01c-41f5-9934-d6f7fdd2d326.png)

The actual error I'd been able to `console.log` directly in the library is : 
```
Unknown arg `missing_property_in_schema` in data.missing_property_in_schema for type UserCreateInput. Did you mean `id`? Available args:`
[...]
```
We'd like to see the error in the frontend client.

### Guess
The problem seems to come from `error-handler.js`.

```
    else if (error instanceof index_1.PrismaClientValidationError) {
        switch (prismaMethod) {
            case 'findUnique':
            case 'remove':
            case 'update':
                feathersError = new errors.NotFound('Record not found.');
                break;
            default:
                break;
        }
    }
```

On line 53 the switch does not set `feathersError` if `prismaMethod` is undefined (which is its value in the case I described above). 
I think it should always set an error (a `errors.GeneralError` maybe ?)

**Comment by ps73** [comment]
I've added an `GeneralError` if prismaMethod is undefined.

Released in [0.3.2](https://www.npmjs.com/package/feathers-prisma)
